### ISSUE TITLE
Build error: Property 'getLineOffsets' does not exist on type 'TextDocument'.

### ISSUE THREAD

**Issue by mickaelistria** [JPinkney/vscode-k8s#31]
I'm trying to build this repo locally:
```
mistria@mistria-rh:~/git/vscode-k8s/server$ npm run compile

> vscode-k8s@0.0.1 compile /home/mistria/git/vscode-k8s/server
> installServerIntoExtension ../client ./package.json ./tsconfig.json && tsc -p .

Copying package.json to extension's server location...
Updating server npm modules into extension's server location...
src/server.ts(171,24): error TS2339: Property 'getLineOffsets' does not exist on type 'TextDocument'.

npm ERR! Linux 4.10.14-200.fc25.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "compile"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! vscode-k8s@0.0.1 compile: `installServerIntoExtension ../client ./package.json ./tsconfig.json && tsc -p .`
npm ERR! Exit status 2
```

**Comment by JPinkney** [comment]
According to the debugger the line document.getLineOffsets() is a valid command (and thats why I used it) but the editor still says its invalid. This leaves some confusion because it resolves to the correct value both when I run it through vs code and in the vs code debugger. I will probably have to write my own getLineOffsets to resolve this

**Comment by mickaelistria** [comment]
Maybe the TextDocument you receive is a specific implementation of the interface, which adds this method. So it's existing at runtime, but at edition time, as the interface only is known, it's not visible.

**Comment by JPinkney** [comment]
Fixed in the master branch
