### ISSUE TITLE
(node:32504) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): TypeError: Cannot read property 'schema' of null

### ISSUE THREAD

**Issue by mickaelistria** [JPinkney/vscode-k8s#32]
When modifying an empty .k8s file, and the language server is connected to it and receive change notification, I always see `(node:32504) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): TypeError: Cannot read property 'schema' of null` in the log. I don't receive diagnostics to show to users.

**Comment by JPinkney** [comment]
I believe what may be happening is that the schema is only registered to .yml files (Happens at the bottom of yamlLanguageService.ts) and attempting to run the language server on .yaml or any other file type will throw a schema error because the schema has not been added to files of that extension. That specific piece of code was there before I started the project but I'll take a look at it

**Comment by JPinkney** [comment]
I've just pushed a quick fix for this by registering the schema for both *.yml and *.yaml files. Let me know if that fixes it

**Comment by mickaelistria** [comment]
I was using a `dummy.k8s` file. Renaming it to `dummy.yml` seems to work: I get some validation error on a yml file from the k8s-ls into the Eclipse IDE! Awesome!

I've got one question about it though: How does the LS decide on which yml files to run? Assuming I have a yml file which is totally unrelated to k8s, would the k8s validation run on it anyway? That would be desired by users.
Aren't there some finer or better conventions for k8s files we could rely on to decide whether to process a file or not?

**Comment by JPinkney** [comment]
That is something that will definitely need to be discussed, in fact the issue was just brought up today by another co-worker (and it was an issue I wasn't even thinking about for some reason when I was assigned this). I'll take a look into it because its currently running on all *.yaml and *.yml files right now

**Comment by JPinkney** [comment]
This should be fixed in master after we transitioned to validating on *.yaml and *.yml files
